// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Flutist

import 'package:flutist/flutist.dart';

/// Extension for package.dependencies.xxx access
extension PackageDependenciesX on List<Dependency> {
  /// Dependency getter for intl
  Dependency get intl => firstWhere((d) => d.name == 'intl');
  /// Dependency getter for test
  Dependency get test => firstWhere((d) => d.name == 'test');
}

/// Extension for package.modules.xxx access
extension PackageModulesX on List<Module> {
  /// Module getter for product_domain
  Module get productDomain => firstWhere((m) => m.name == 'product_domain');
  /// Module getter for product_data
  Module get productData => firstWhere((m) => m.name == 'product_data');
  /// Module getter for product_presentation
  Module get productPresentation => firstWhere((m) => m.name == 'product_presentation');
}
