name: product_presentation
description: A Flutter module
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter_bloc: ^8.1.4
  product_domain:
    path: ../product_domain

resolution: workspace