name: app
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  product_presentation:
    path: ../features/product/product_presentation
  product_data:
    path: ../features/product/product_data
  cart_presentation:
    path: ../features/cart/cart_presentation
  cart_data:
    path: ../features/cart/cart_data

resolution: workspace